version: '3.7' # standard version

services: # declare containers: nginx and app
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'always'
  app:
    container_name: api-dev-server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    volumes:
      - ./.env:/app/.env
      - ./ormconfig.json:/app/ormconfig.json
