version: '3.7' # 파일 규격 버전

services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'always'
  app:
    container_name: api-dev-server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    volumes:
      - ./.env:/app/.env
      - ./ormconfig.json:/app/ormconfig.json
